DROP TABLE IF EXISTS posts;

CREATE TABLE posts (
    id INTEGER PRIMARY KEY AUTOINCREMENT,
    created TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    title TEXT NOT NULL,
    contato INTEGER,
    email TEXT,
    content TEXT NOT NULL,
    tipo CHAR NOT NULL DEFAULT 'M'
);
